version: '3.1'
services:

  monolit-db:
    image: postgres:12.3-alpine
    container_name: monolit_postgres
    ports:
      - ${MONOLIT_DB_PORT}:5432
    volumes:
      - ./pg_data/monolit:${MONOLIT_PGDATA_DB}
    environment:
      POSTGRES_USER: ${MONOLIT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${MONOLIT_POSTGRES_PASSWORD}
      POSTGRES_DB: ${MONOLIT_POSTGRES_NAME_DB}
      PGDATA: ${MONOLIT_PGDATA_DB}

  monolit:
    build:
      context: Monolit
      dockerfile: monolit.dockerfile
    container_name: monolit
    ports:
      - ${MONOLIT_PORT}:${MONOLIT_PORT}
    volumes:
      - ./back_data:/opt/server/logs
    environment:
      POSTGRES_HOST: monolit-db
      POSTGRES_USER: ${MONOLIT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${MONOLIT_POSTGRES_PASSWORD}
      POSTGRES_DB: ${MONOLIT_POSTGRES_NAME_DB}
      MONOLIT_PORT: ${MONOLIT_PORT}
      GRAPHQL_ENDPOINT_URI: ${GRAPHQL_ENDPOINT_URI}
      HOST_PREFIX: ${HOST_PREFIX}
      EUREKA_HOST: ${HOST_PREFIX}${EUREKA_SERVER_SYSTEM_LOGIN}:${EUREKA_SERVER_SYSTEM_PASSWORD}@monitor:${EUREKA_SERVER_PORT}/eureka
    links:
      - monitor
    depends_on:
      - monolit-db

  auth-db:
    image: postgres:12.3-alpine
    container_name: auth_postgres
    ports:
      - ${AUTH_DB_PORT}:5432
    volumes:
      - ./pg_data/auth:${AUTH_PGDATA_DB}
    environment:
      POSTGRES_USER: ${AUTH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AUTH_POSTGRES_NAME_DB}
      PGDATA: ${AUTH_PGDATA_DB}

  auth-service:
    build:
      context: AuthService
      dockerfile: AuthServise-dev.dockerfile
    container_name: auth-service
    ports:
    - ${AUTH_PORT}:8090
    environment:
      POSTGRES_HOST: auth-db
      POSTGRES_USER: ${AUTH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AUTH_POSTGRES_NAME_DB}
      AUTH_PORT: ${AUTH_PORT}
      HOST_PREFIX: ${HOST_PREFIX}
      EUREKA_HOST: ${HOST_PREFIX}${EUREKA_SERVER_SYSTEM_LOGIN}:${EUREKA_SERVER_SYSTEM_PASSWORD}@monitor:${EUREKA_SERVER_PORT}/eureka
    links:
      - monitor
    depends_on:
      - auth-db

  monitor:
    build:
      context: Monitor
      dockerfile: dockerfile-admin-eureka.dockerfile
    container_name: monitor
    ports:
      - ${EUREKA_SERVER_PORT}:${EUREKA_SERVER_PORT}
    volumes:
      - ./back_data:/opt/server/logs
    environment:
      EUREKA_SERVER_PORT: ${EUREKA_SERVER_PORT}
      EUREKA_SERVER_SYSTEM_LOGIN: ${EUREKA_SERVER_SYSTEM_LOGIN}
      EUREKA_SERVER_SYSTEM_PASSWORD: ${EUREKA_SERVER_SYSTEM_PASSWORD}
      EUREKA_SERVER_ADMIN_LOGIN: ${EUREKA_SERVER_ADMIN_LOGIN}
      EUREKA_SERVER_ADMIN_PASSWORD: ${EUREKA_SERVER_ADMIN_PASSWORD}
      EUREKA_CLIENT_URI: ${EUREKA_CLIENT_URI}

  proxy-redis:
    build:
      context: Gateway
      dockerfile: redis.dockerfile
    container_name: proxy-redis
    ports:
      - ${GATEWAYJ_REDIS_PORT}:${GATEWAYJ_REDIS_PORT}

  proxy:
    build:
      context: Gateway
      dockerfile: gateway.dockerfile
    container_name: proxy
    ports:
      - ${GATEWAYJ_PORT}:${GATEWAYJ_PORT}
    volumes:
      - ./back_data:/opt/server/logs
    environment:
      HOST_PREFIX: ${HOST_PREFIX}
      EUREKA_HOST: ${HOST_PREFIX}${EUREKA_SERVER_SYSTEM_LOGIN}:${EUREKA_SERVER_SYSTEM_PASSWORD}@monitor:${EUREKA_SERVER_PORT}/eureka
      GATEWAYJ_PORT: ${GATEWAYJ_PORT}
      REDIS_HOST: proxy-redis
    depends_on:
      - proxy-redis
    links:
      - monitor
