######################### App configurations ############################################
server:
  port: 8070

spring:
  application:
    name: email-sender
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
    loadbalancer:
      ribbon:
        enabled: false
  ######################### rabbitmq config ############################
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    host: localhost
    template:
      exchange: messages-broker.direct
      routing-key: notification.email
      queue: notification.email.queue
######################### Email config ############################
  mail:
    host: smtp.gmail.com
    port: 465
    protocol: smtps
    username: teeneducationportal@gmail.com
    password: GodOfDeathLikesApples
    properties:
      mail:
        transport.protocol: smtps
        smtps:
          auth: true
          starttls.enable: true
          timeout: 8000
support.email: teeneducationportal@gmail.com
######################### SPRING BOOT ADMIN CLIENT #########################
management:
  endpoint:
    shutdown.enabled: true
    heapdump.enabled: false
    health.show-details: always
  endpoints:
    enabled-by-default: true
    web.exposure.include: "*"

######################### EUREKA client config ############################
eureka:
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: false
    metadata-map:
      user.name: ACTUATOR_LOGIN         #These two are needed so that the server
      user.password: ACTUATOR_PASSWORD    #can access the protected client endpoints
  client:
    registryFetchIntervalSeconds: 30
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://system:system@localhost:8761/eureka
    healthcheck:
      enabled: true
#instance.preferIpAddress в true и, когда приложение регистрируется в eureka, оно использует свой IP-адрес, а не имя хоста.

